manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
# Kinematics solver doesn't support attempts anymore in noetic (possibly also melodic)
# add back (uncomment) if needed:
#  kinematics_solver_attempts: 3
